# Generated by Django 4.0.2 on 2022-02-25 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFRequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=10)),
                ('control_number', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('date_filed', models.DateField()),
                ('request_type', models.CharField(max_length=50)),
                ('requester_id', models.CharField(max_length=50)),
                ('requester_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AFTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AFType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_number', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('series_length', models.IntegerField()),
                ('use_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AFUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('af_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accountableForms.aftype')),
            ],
        ),
        migrations.CreateModel(
            name='AFTransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=10)),
                ('control_number', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('date_filed', models.DateField()),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=255)),
                ('issued_id', models.CharField(max_length=50)),
                ('issued_name', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=50)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accountableForms.afrequesthistory')),
            ],
        ),
        migrations.CreateModel(
            name='AFRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('af_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accountableForms.aftype')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accountableForms.afrequesthistory')),
            ],
        ),
    ]
