# Generated by Django 4.0.2 on 2022-02-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_alter_user_tnxcode_user_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
