# Generated by Django 4.0.2 on 2022-03-08 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AFInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AFIssuingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AFPrefix',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AFPurchaseTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AFRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.afprefix')),
            ],
        ),
        migrations.CreateModel(
            name='AFState',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AFTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=50)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('issueing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.afissuingrecord')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.afprefix')),
                ('request_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.afrequesthistory')),
            ],
        ),
        migrations.CreateModel(
            name='AFTransactionStatus',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AFTransactionType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AFType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('series_length', models.IntegerField()),
                ('use_type', models.CharField(max_length=50, null=True)),
                ('unit', models.CharField(default='STUB', max_length=25)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AFTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('af_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftype')),
                ('transaction_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftransactionhistory')),
            ],
        ),
        migrations.AddField(
            model_name='aftransactionhistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftransactionstatus'),
        ),
        migrations.AddField(
            model_name='aftransactionhistory',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftransactiontype'),
        ),
        migrations.CreateModel(
            name='AFRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('af_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftype')),
                ('request_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.afrequesthistory')),
            ],
        ),
        migrations.AddField(
            model_name='afrequesthistory',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftransactiontype'),
        ),
        migrations.AddField(
            model_name='afrequesthistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftransactionstatus'),
        ),
        migrations.CreateModel(
            name='AFInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_series', models.IntegerField()),
                ('current_series', models.IntegerField()),
                ('end_series', models.IntegerField()),
                ('stub_number', models.IntegerField()),
                ('active', models.BooleanField()),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('af_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftype')),
            ],
        ),
    ]
