# Generated by Django 4.0.2 on 2022-02-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountable_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftype',
            name='series_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aftype',
            name='use_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
