# Generated by Django 4.0.2 on 2022-03-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountable_forms', '0002_alter_afrequesthistory_control_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFPurchaseTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_series', models.IntegerField()),
                ('end_series', models.IntegerField()),
                ('stub_number', models.IntegerField()),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AFInventoryItem',
            new_name='AFItem',
        ),
        migrations.DeleteModel(
            name='AFPurchaseTransactionHistory',
        ),
        migrations.AddField(
            model_name='aftransactionitem',
            name='request_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.afrequestitem'),
        ),
        migrations.AlterField(
            model_name='afrequesthistory',
            name='control_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='afrequesthistory',
            name='prefix',
            field=models.ForeignKey(default='PREFIX_REQUEST', on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.afprefix'),
        ),
        migrations.AlterField(
            model_name='afrequesthistory',
            name='request_type',
            field=models.ForeignKey(default='TYPE_REQUEST', on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftransactiontype'),
        ),
        migrations.AlterField(
            model_name='afrequesthistory',
            name='status',
            field=models.ForeignKey(default='STATUS_PENDING', on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftransactionstatus'),
        ),
        migrations.AlterField(
            model_name='aftransactionhistory',
            name='control_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aftransactionhistory',
            name='prefix',
            field=models.ForeignKey(default='PREFIX_TRANSACTION', on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.afprefix'),
        ),
        migrations.AddField(
            model_name='afpurchasetransactionitem',
            name='transaction_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftransactionitem'),
        ),
    ]
