# Generated by Django 4.0.2 on 2022-03-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountable_forms', '0003_afpurchasetransactionitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftransactionhistory',
            name='status',
            field=models.ForeignKey(default='STATUS_PENDING', on_delete=django.db.models.deletion.RESTRICT, to='accountable_forms.aftransactionstatus'),
        ),
    ]
